[build]
builder = "dockerfile"
dockerfilePath = "Dockerfile.railway"

[deploy]
startCommand = "/app/start-postal.sh"
healthcheckPath = "/health"
healthcheck = "disabled"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
